### ISSUE TITLE
Blog feed url

### ISSUE THREAD

**Issue by harikt** [oddbird/susy.oddbird.net#1]
Hi,

I came across susy recently. Good work on it. Going though I thought of subscribing to the feeds,  http://susy.oddbird.net/demos/ . From the url I got http://susy.oddbird.net/feed.atom , but it looks not.

I am wondering how is the website being generated to html. Probably some sort of script may be behind the scene. Is there a way we can get the feeds working ?

Thank you.

**Comment by mirisuzanne** [comment]
I'm using rstBlog to generate the site. I've set it up so there could be a blog, which must be why it is generating a feed link, but currently there have not been any posts. I think you have the right link. What you need to do now is convince someone to post something...

**Comment by harikt** [comment]
I thought the tutorial link which point to demos is also a blog. I may want to look more on to this.

Closing for the current time for it is right according to you.

Thank you.

**Comment by mirisuzanne** [comment]
Nope. The tutorials are also built by the rstBlog generator, but they aren't actually "blog posts" according to that system - they're just pages.

**Comment by harikt** [comment]
ok. So may be the fix is need for rstBlog generator :) .
